[build]
base = "site/"
command = "yarn build"
publish = "build"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../sites.yml"


[build.environment]
NODE_VERSION = "16.9.0"
YARN_VERSION = "1.22.10"
