[build]
base = "site/"
command = "yarn build"
publish = "build"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../sites.yml"


[build.environment]
NODE_VERSION = "17.0.1"
YARN_VERSION = "1.22.17"
