name: Link check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # monthly

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'janosh'
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        # docs at https://git.io/JBaKu
        with:
          # sets status code 500 (Internal Server Error) and 503 (Service Unavailable) as alive
          config-file: utils/markdown_link_check_config.json
