name: Linter

on: [push, pull_request]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run markdownlint
        uses: reviewdog/action-markdownlint@master
        # docs at https://git.io/JBaid
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        # docs at https://git.io/JBaKu
        with:
          # sets status code 500 (Internal Server Error) and 503 (Service Unavailable) as alive
          config-file: .github/workflows/markdown_link_check_config.json

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        # docs at https://git.io/JBa6q
        with:
          config_file: .github/.yamllint.yml
