name: Update readme + site screenshots on changed sites.yml

on:
  pull_request:
    branches: [main]
    paths: [sites.yml, site/scripts/*]
  push:
    branches: [main]
    paths: [sites.yml, site/scripts/*]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */3 *' # https://crontab.guru/every-quarter

jobs:
  new-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn
          cache-dependency-path: site/yarn.lock

      - name: Install dependencies
        run: yarn add puppeteer js-yaml imagemin imagemin-webp

      - name: Update existing screenshots on scheduled runs
        if: github.event_name == 'schedule'
        run: node site/scripts/screenshots.js update-existing

      - name: Add screenshots for new sites and update readme
        if: github.event_name != 'schedule'
        run: |
          node site/scripts/screenshots.js
          node site/scripts/readmeSiteList.js

      - name: Push changes if any
        run: |
          if git diff --quiet site/static/screenshots readme.md; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name 'Janosh Riebesell'
          git config user.email janosh.riebesell@gmail.com
          git add readme.md site/static/screenshots
          git commit -m 'update readme + screenshots'
          git push
