name: Update Site Screenshots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */3 *' # https://crontab.guru/every-quarter

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn add puppeteer js-yaml

      - name: Run takeScreenshots.js
        run: node site/scripts/takeScreenshots.js update-existing

      - name: Push new screenshots
        run: |
          if git diff --quiet site/static/screenshots; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name 'Janosh Riebesell'
          git config user.email janosh.riebesell@gmail.com
          git commit -a -m 'update site screenshots'
          git push
